-- Nodrog Logistics — real fleet vehicles (IGL + Massy)
-- Imported from the June 2026 Weekly Report workbooks.
-- Safe to re-run: upserts on (fleet, plate). Run in Supabase SQL Editor.

create unique index if not exists trucks_fleet_plate_uniq on public.trucks (fleet, plate);

insert into public.trucks
  (fleet, plate, model, segment, chassis, capacity, driver, location, status, odometer, idle_hrs, service, insurance_exp, fitness_exp, mv_reg_exp, carrier_lic_exp, fire_ext_date)
values
  ('MASSY','CF2947','2002 Freightliner FL80','Bulk',NULL,'3000 USG',NULL,'Freeport','oos',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CH4824','2010 Freightliner CL112','Bulk','1FVHF0A89ALAR514D','5000 USG','Conroy Allen','Freeport','ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,'2024-03-18','2024-03-31','2024-03-31',NULL),
  ('MASSY','CL0182','2016 Kenworth T800','Bulk','1NKDL09XOGR123391','5400 USG','Tuson Coke','Freeport','ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,'2024-01-04','2024-03-31','2024-03-31',NULL),
  ('MASSY','CK1361','2014 Kenworth T800','Bulk',NULL,'5000 USG','Calbert Watson','KGN','oos',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CL0181','2021 Kenworth T800','Bulk','1NKDL09X9GR123390','5000 USG','Hasani Green','Freeport','ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,'2024-04-01','2024-03-31','2024-03-31',NULL),
  ('MASSY','TT6160','Trailer (Propane/Butane)','Trailer',NULL,'7500 USG','Orlando Gordon','Freeport','ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,'2023-09-30',NULL,'2023-03-31',NULL,NULL),
  ('MASSY','TT6162','Trailer (Propane/Butane)','Trailer',NULL,'7500 USG',NULL,'KGN','ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,'2023-09-30',NULL,NULL,NULL,NULL),
  ('MASSY','TT026B','Trailer','Trailer',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','TT3702','Trailer','Trailer',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','TT190C','Trailer (LNG)','Trailer',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CP1981','Hino Pack Truck','Pack',NULL,NULL,NULL,NULL,'oos',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CS2577','Pack Truck','Pack',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CT7382','Hino 300','Pack',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CT7377','Hino 300','Pack',NULL,NULL,NULL,NULL,'oos',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CT7376','Hino 300','Pack',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CT2245','Isuzu Elf','Pack',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('MASSY','CU1045','Shacman L3000','Pack',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CS1929','International DuraStar',NULL,NULL,NULL,'Ruhg Ried',NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CJ1723','International 8600',NULL,NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CJ0784','International',NULL,NULL,NULL,'Henry Harty',NULL,'oos',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CJ7923','International Bobtail',NULL,NULL,NULL,'Adriel Fisher',NULL,'oos',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CH6490',NULL,NULL,NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CM0673',NULL,NULL,NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CN3178','Mitsubishi Fuso Pack Truck','Pack',NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CS9912','Mitsubishi Fuso Pack Truck','Pack',NULL,NULL,'Tristan Maxwell',NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CN3177','Mitsubishi Fuso Pack Truck','Pack',NULL,NULL,'Audley Radcliffe',NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CN3179','Mitsubishi Fuso Pack Truck','Pack',NULL,NULL,'Satan Johnson',NULL,'ok',96492,11369.5,'{"engine":{"lastMiles":96492,"lastIdleHrs":11369.5,"date":"2025-02-02","nextDueMiles":104492,"nextDueHrs":11869.5},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":"2025-08-24"},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CN3190','Mitsubishi Fuso Pack Truck','Pack',NULL,NULL,'Rechardo Vanriel',NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL),
  ('IGL','CJ0673',NULL,NULL,NULL,NULL,NULL,NULL,'ok',0,0,'{"engine":{"lastMiles":0,"lastIdleHrs":0,"date":"","nextDueMiles":8000,"nextDueHrs":500},"transmission":{"lastMiles":0,"lastIdleHrs":0,"date":""},"airFilter":{"lastMiles":0,"date":""},"frontDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""},"rearDiff":{"lastMiles":0,"lastIdleHrs":0,"date":""}}'::jsonb,NULL,NULL,NULL,NULL,NULL)
on conflict (fleet, plate) do update set
  model = excluded.model, segment = excluded.segment, chassis = excluded.chassis,
  capacity = excluded.capacity, driver = excluded.driver, location = excluded.location,
  status = excluded.status, insurance_exp = excluded.insurance_exp, fitness_exp = excluded.fitness_exp,
  mv_reg_exp = excluded.mv_reg_exp, carrier_lic_exp = excluded.carrier_lic_exp;
